name: Deploy Quasar App

on:
  push:
    branches:
      - main  # 你可以根据你的主分支名称进行调整

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # 你可以根据你的项目需求选择合适的 Node.js 版本

    - name: Install dependencies
      run: yarn install  # 或者使用 npm install

    - name: Build Quasar App
      run: yarn quasar build  # 或者使用 npm run build
      uses: appleboy/scp-action@v0.1.1
    - name: Deploy to Server
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录
          build_dir: dist
          